package spec

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/JadenB9/projectmaker/internal/config"
	"github.com/JadenB9/projectmaker/internal/scaffold"
)

// envEntry describes an environment variable for the spec doc.
type envEntry struct {
	Variable   string
	WhereToGet string
}

// Generate writes a PROJECT_SPEC.md file into cfg.ProjectDir that serves as
// the source-of-truth document for the scaffolded project.
func Generate(cfg *config.ProjectConfig, result *scaffold.Result) error {
	today := time.Now().Format("2006-01-02")

	var b strings.Builder

	writeHeader(&b, cfg, today)
	writeManualSteps(&b, result)      // Manual steps first so users see them immediately
	writeProjectInfo(&b, cfg, today)
	writeStackSummary(&b, cfg)
	writeEnvVars(&b, cfg)
	writeDevCommands(&b, cfg)
	writeDeployment(&b, cfg)
	writeArchNotes(&b, cfg)
	writeAIInstructions(&b, cfg)      // AI-specific guidance at the end

	specPath := filepath.Join(cfg.ProjectDir, "PROJECT_SPEC.md")
	if err := os.WriteFile(specPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("writing PROJECT_SPEC.md: %w", err)
	}

	result.SpecPath = specPath
	return nil
}

// writeHeader outputs the top-level heading and generator badge.
func writeHeader(b *strings.Builder, cfg *config.ProjectConfig, date string) {
	b.WriteString(fmt.Sprintf("# %s — Project Specification\n\n", cfg.Name))
	b.WriteString(fmt.Sprintf("> Generated by [projectmaker](https://github.com/JadenB9/projectmaker) on %s\n\n", date))
}

// writeManualSteps lists scaffold steps that still need manual action.
// This is placed near the top so the user sees it first.
func writeManualSteps(b *strings.Builder, result *scaffold.Result) {
	var manual []scaffold.StepResult
	for _, s := range result.Steps {
		if s.Status == "manual" {
			manual = append(manual, s)
		}
	}

	if len(manual) == 0 {
		b.WriteString("## Setup Status\n\n")
		b.WriteString("All setup steps completed automatically. No manual action needed.\n\n")
		return
	}

	b.WriteString("## Manual Setup Required\n\n")
	b.WriteString("The following steps could not be automated and need your attention:\n\n")
	for i, s := range manual {
		b.WriteString(fmt.Sprintf("%d. **%s:** %s\n", i+1, s.Name, s.Message))
	}
	b.WriteString("\nComplete these steps before starting development.\n\n")
}

// writeProjectInfo outputs basic project metadata.
func writeProjectInfo(b *strings.Builder, cfg *config.ProjectConfig, date string) {
	b.WriteString("## Project Info\n\n")
	b.WriteString(fmt.Sprintf("- **Name:** %s\n", cfg.Name))
	b.WriteString(fmt.Sprintf("- **Directory:** `%s`\n", cfg.ProjectDir))
	if cfg.Stack != "" {
		b.WriteString(fmt.Sprintf("- **Stack:** %s\n", cfg.Stack))
	}
	b.WriteString(fmt.Sprintf("- **Created:** %s\n", date))
	b.WriteString("\n")
}

// writeStackSummary outputs a markdown table of every non-empty stack choice.
func writeStackSummary(b *strings.Builder, cfg *config.ProjectConfig) {
	type row struct {
		Layer string
		Value string
	}

	rows := []row{
		{"Language", cfg.Language},
		{"Framework", cfg.Framework},
		{"Styling", cfg.Styling},
		{"Backend", cfg.Backend},
		{"Database", cfg.Database},
		{"Auth", cfg.Auth},
		{"Payments", cfg.Payments},
		{"Email", cfg.Email},
		{"Package Manager", cfg.PackageManager},
		{"Deployment", strings.Join(cfg.Deployment, ", ")},
	}

	var filtered []row
	for _, r := range rows {
		if r.Value != "" && r.Value != "none" {
			filtered = append(filtered, r)
		}
	}

	if len(filtered) == 0 {
		return
	}

	b.WriteString("## Stack Summary\n\n")
	b.WriteString("| Layer | Choice |\n")
	b.WriteString("|-------|--------|\n")
	for _, r := range filtered {
		b.WriteString(fmt.Sprintf("| %s | %s |\n", r.Layer, r.Value))
	}
	b.WriteString("\n")
}

// writeEnvVars outputs a table of every environment variable with instructions.
func writeEnvVars(b *strings.Builder, cfg *config.ProjectConfig) {
	entries := collectEnvEntries(cfg)
	if len(entries) == 0 {
		return
	}

	b.WriteString("## Environment Variables\n\n")
	b.WriteString("| Variable | Where to Get It |\n")
	b.WriteString("|----------|----------------|\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("| `%s` | %s |\n", e.Variable, e.WhereToGet))
	}
	b.WriteString("\n")
}

func collectEnvEntries(cfg *config.ProjectConfig) []envEntry {
	var entries []envEntry

	switch cfg.Database {
	case "prisma", "drizzle":
		entries = append(entries, envEntry{"DATABASE_URL", "Your database provider"})
	case "supabase":
		entries = append(entries,
			envEntry{"NEXT_PUBLIC_SUPABASE_URL", "[Supabase Dashboard](https://supabase.com/dashboard) > Settings > API"},
			envEntry{"NEXT_PUBLIC_SUPABASE_ANON_KEY", "[Supabase Dashboard](https://supabase.com/dashboard) > Settings > API"},
			envEntry{"SUPABASE_SERVICE_ROLE_KEY", "[Supabase Dashboard](https://supabase.com/dashboard) > Settings > API"},
		)
	case "mongodb-mongoose":
		entries = append(entries, envEntry{"MONGODB_URI", "[MongoDB Atlas](https://cloud.mongodb.com) > Database > Connect"})
	}

	switch cfg.Auth {
	case "clerk":
		entries = append(entries,
			envEntry{"NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY", "[Clerk Dashboard](https://dashboard.clerk.com) > API Keys"},
			envEntry{"CLERK_SECRET_KEY", "[Clerk Dashboard](https://dashboard.clerk.com) > API Keys"},
		)
	case "nextauth":
		entries = append(entries,
			envEntry{"NEXTAUTH_URL", "Set to `http://localhost:3000` for local dev"},
			envEntry{"NEXTAUTH_SECRET", "Run: `openssl rand -base64 32`"},
		)
	}

	if cfg.Payments == "stripe" {
		entries = append(entries,
			envEntry{"STRIPE_SECRET_KEY", "[Stripe Dashboard](https://dashboard.stripe.com) > Developers > API keys"},
			envEntry{"NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY", "[Stripe Dashboard](https://dashboard.stripe.com) > Developers > API keys"},
			envEntry{"STRIPE_WEBHOOK_SECRET", "[Stripe Dashboard](https://dashboard.stripe.com) > Developers > Webhooks"},
		)
	}

	if cfg.Email == "resend" {
		entries = append(entries, envEntry{"RESEND_API_KEY", "[Resend Dashboard](https://resend.com/api-keys)"})
	}

	return entries
}

// writeDevCommands outputs relevant dev/build/lint/test commands.
func writeDevCommands(b *strings.Builder, cfg *config.ProjectConfig) {
	if cfg.Framework == "" || cfg.Framework == "none" {
		return
	}

	b.WriteString("## Development Commands\n\n")
	b.WriteString("```bash\n")

	pm := cfg.PackageManager
	if pm == "" {
		pm = "npm"
	}

	run := pm + " run "
	if pm == "bun" {
		run = "bun "
	}

	switch cfg.Framework {
	case "nextjs":
		b.WriteString(fmt.Sprintf("%sdev        # Start dev server\n", run))
		b.WriteString(fmt.Sprintf("%sbuild      # Production build\n", run))
		b.WriteString(fmt.Sprintf("%sstart      # Start production server\n", run))
		b.WriteString(fmt.Sprintf("%slint       # Run ESLint\n", run))
	case "react-vite", "sveltekit", "nuxt":
		b.WriteString(fmt.Sprintf("%sdev        # Start dev server\n", run))
		b.WriteString(fmt.Sprintf("%sbuild      # Production build\n", run))
		b.WriteString(fmt.Sprintf("%spreview    # Preview production build\n", run))
	case "django":
		b.WriteString("python manage.py runserver   # Start dev server\n")
		b.WriteString("python manage.py migrate     # Run migrations\n")
		b.WriteString("python manage.py test        # Run tests\n")
	case "fastapi":
		b.WriteString("uvicorn main:app --reload    # Start dev server\n")
		b.WriteString("pytest                       # Run tests\n")
	case "rails":
		b.WriteString("rails server       # Start dev server\n")
		b.WriteString("rails db:migrate   # Run migrations\n")
		b.WriteString("rails test         # Run tests\n")
	case "laravel":
		b.WriteString("php artisan serve      # Start dev server\n")
		b.WriteString("php artisan migrate    # Run migrations\n")
		b.WriteString("php artisan test       # Run tests\n")
	default:
		b.WriteString(fmt.Sprintf("%sdev        # Start dev server\n", run))
		b.WriteString(fmt.Sprintf("%sbuild      # Production build\n", run))
	}

	b.WriteString("```\n\n")
}

// writeDeployment outputs deployment instructions for all configured targets.
func writeDeployment(b *strings.Builder, cfg *config.ProjectConfig) {
	if len(cfg.Deployment) == 0 {
		return
	}

	b.WriteString("## Deployment\n\n")

	for _, dep := range cfg.Deployment {
		switch dep {
		case "vercel":
			b.WriteString("### Vercel (frontend / serverless)\n\n")
			b.WriteString("Push to GitHub (auto-deploys if linked) or run:\n\n")
			b.WriteString("```bash\nvercel --prod\n```\n\n")
		case "railway":
			b.WriteString("### Railway (backend / services)\n\n")
			b.WriteString("1. Go to [railway.app](https://railway.app) and create a new project\n")
			b.WriteString("2. Deploy from your GitHub repository\n")
			b.WriteString("3. Add environment variables in the Railway dashboard\n\n")
		case "cloudflare":
			b.WriteString("### Cloudflare (DNS / CDN / edge)\n\n")
			b.WriteString("1. Go to the [Cloudflare dashboard](https://dash.cloudflare.com)\n")
			b.WriteString("2. Add your domain for DNS management\n")
			b.WriteString("3. For Pages: create a project and connect your GitHub repo\n")
			b.WriteString("4. For Workers: use `wrangler` CLI to deploy edge functions\n\n")
		case "docker":
			b.WriteString("### Docker (self-hosted)\n\n")
			b.WriteString("```bash\n")
			b.WriteString(fmt.Sprintf("docker build -t %s .\n", cfg.Name))
			b.WriteString(fmt.Sprintf("docker run -p 3000:3000 %s\n", cfg.Name))
			b.WriteString("```\n\n")
		case "aws":
			b.WriteString("### AWS\n\n")
			b.WriteString("1. Configure AWS CLI: `aws configure`\n")
			b.WriteString("2. Choose your service: Lambda (serverless), ECS (containers), or EC2 (VMs)\n")
			b.WriteString("3. Set up environment variables in your chosen service's console\n\n")
		case "flyio":
			b.WriteString("### Fly.io (global edge)\n\n")
			b.WriteString("1. Install flyctl: `curl -L https://fly.io/install.sh | sh`\n")
			b.WriteString("2. Launch: `fly launch`\n")
			b.WriteString("3. Deploy: `fly deploy`\n\n")
		}
	}
}

// writeArchNotes outputs a brief description of how the pieces connect.
func writeArchNotes(b *strings.Builder, cfg *config.ProjectConfig) {
	if cfg.Framework == "" && cfg.Language == "" {
		return
	}

	b.WriteString("## Architecture Notes\n\n")

	if cfg.Framework != "" && cfg.Framework != "none" {
		b.WriteString(fmt.Sprintf("This is a **%s** project", cfg.Framework))
		if cfg.Language != "" && cfg.Language != "none" {
			b.WriteString(fmt.Sprintf(" written in **%s**", cfg.Language))
		}
		b.WriteString(".\n\n")
	} else if cfg.Language != "" && cfg.Language != "none" {
		b.WriteString(fmt.Sprintf("This is a **%s** project.\n\n", cfg.Language))
	}

	switch cfg.Database {
	case "prisma":
		b.WriteString("**Database:** Prisma ORM for type-safe database access. Schema in `prisma/schema.prisma`.\n\n")
	case "drizzle":
		b.WriteString("**Database:** Drizzle ORM for lightweight, type-safe SQL.\n\n")
	case "supabase":
		b.WriteString("**Database:** Supabase for managed Postgres with auth and real-time.\n\n")
	case "mongodb-mongoose":
		b.WriteString("**Database:** MongoDB with Mongoose ODM.\n\n")
	}

	switch cfg.Auth {
	case "clerk":
		b.WriteString("**Auth:** Clerk for authentication and user management.\n\n")
	case "nextauth":
		b.WriteString("**Auth:** NextAuth.js for flexible multi-provider authentication.\n\n")
	case "lucia":
		b.WriteString("**Auth:** Lucia for lightweight session-based auth.\n\n")
	}

	if cfg.Payments == "stripe" {
		b.WriteString("**Payments:** Stripe for payment processing and subscriptions.\n\n")
	}

	if cfg.Email == "resend" {
		b.WriteString("**Email:** Resend for transactional email delivery.\n\n")
	}
}

// writeAIInstructions outputs guidelines for AI tools working in this project.
func writeAIInstructions(b *strings.Builder, cfg *config.ProjectConfig) {
	b.WriteString("---\n\n")
	b.WriteString("## AI Development Guidelines\n\n")
	b.WriteString("The following instructions are for any AI assistant (Claude, Copilot, ChatGPT, etc.) that works on this project. These rules are non-negotiable.\n\n")

	b.WriteString("### Git Attribution\n\n")
	b.WriteString("Never include `Co-Authored-By` lines, AI attribution, or any indication of AI involvement in commit messages. ")
	b.WriteString("All commits must look like they were written by the repository owner. ")
	b.WriteString("Do not add comments like `// Generated by AI` or `// Copilot suggestion` anywhere in the code. ")
	b.WriteString("The git history should reflect a single human author working on their project.\n\n")

	b.WriteString("### Code Style — Student Written\n\n")
	b.WriteString("All code in this project should read as if it were written by a computer science student. ")
	b.WriteString("Avoid overly polished patterns, excessive abstraction, or enterprise-grade architecture that a student wouldn't naturally produce. ")
	b.WriteString("Use clear variable names and straightforward logic. Add comments where a student would — to explain tricky parts, not to document the obvious. ")
	b.WriteString("Keep the code clean and well-organized, but don't over-engineer. A student writes practical, working code — not showcase code. ")
	b.WriteString("Avoid hallmarks of AI-generated code: don't add unnecessary type annotations everywhere, don't create abstractions for things used once, and don't add defensive error handling for impossible cases.\n\n")

	b.WriteString("### Security First\n\n")
	b.WriteString("Every piece of code in this project must be written with security as a primary concern. ")
	b.WriteString("Never hardcode secrets, API keys, passwords, or credentials — always use environment variables via `.env`. ")
	b.WriteString("Validate and sanitize all user input before processing. Use parameterized queries for database access — never concatenate user input into SQL strings. ")
	b.WriteString("Implement proper authentication and authorization checks on every protected route. ")
	b.WriteString("Set appropriate CORS policies, use HTTPS everywhere, and follow the principle of least privilege. ")
	b.WriteString("When in doubt about a security decision, choose the more restrictive option. Review the OWASP Top 10 and ensure none of those vulnerabilities are present.\n\n")

	// GitHub connection info
	b.WriteString("### GitHub Connection\n\n")
	b.WriteString(fmt.Sprintf("This project is connected to GitHub as `%s`. ", cfg.Name))
	b.WriteString("The `.env` file is excluded from version control via `.gitignore`. ")
	b.WriteString("The `.env.example` file shows which environment variables are needed without exposing actual values. ")
	b.WriteString("Never commit secrets to the repository, even temporarily — they persist in git history forever.\n\n")
}
