package spec

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/JadenB9/projectmaker/internal/config"
	"github.com/JadenB9/projectmaker/internal/scaffold"
)

// envEntry describes an environment variable for the spec doc.
type envEntry struct {
	Variable   string
	WhereToGet string
}

// Generate writes a PROJECT_SPEC.md file into cfg.ProjectDir that serves as
// the source-of-truth document for the scaffolded project.
func Generate(cfg *config.ProjectConfig, result *scaffold.Result) error {
	today := time.Now().Format("2006-01-02")

	var b strings.Builder

	writeHeader(&b, today)
	writeProjectInfo(&b, cfg, today)
	writeStackSummary(&b, cfg)
	writeEnvVars(&b, cfg)
	writeManualSteps(&b, result)
	writeDevCommands(&b, cfg)
	writeDeployment(&b, cfg)
	writeArchNotes(&b, cfg)

	specPath := filepath.Join(cfg.ProjectDir, "PROJECT_SPEC.md")
	if err := os.WriteFile(specPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("writing PROJECT_SPEC.md: %w", err)
	}

	result.SpecPath = specPath
	return nil
}

// writeHeader outputs the top-level heading and generator badge.
func writeHeader(b *strings.Builder, date string) {
	b.WriteString("# Project Specification\n\n")
	b.WriteString(fmt.Sprintf("> Generated by [projectmaker](https://github.com/JadenB9/projectmaker) on %s\n\n", date))
}

// writeProjectInfo outputs basic project metadata.
func writeProjectInfo(b *strings.Builder, cfg *config.ProjectConfig, date string) {
	b.WriteString("## Project Info\n\n")
	b.WriteString(fmt.Sprintf("- **Name:** %s\n", cfg.Name))
	b.WriteString(fmt.Sprintf("- **Directory:** `%s`\n", cfg.ProjectDir))
	b.WriteString(fmt.Sprintf("- **Stack:** %s\n", cfg.Stack))
	b.WriteString(fmt.Sprintf("- **Created:** %s\n", date))
	b.WriteString("\n")
}

// writeStackSummary outputs a markdown table of every non-empty stack choice.
func writeStackSummary(b *strings.Builder, cfg *config.ProjectConfig) {
	type row struct {
		Layer string
		Value string
	}

	rows := []row{
		{"Language", cfg.Language},
		{"Framework", cfg.Framework},
		{"Styling", cfg.Styling},
		{"Backend", cfg.Backend},
		{"Database", cfg.Database},
		{"Auth", cfg.Auth},
		{"Payments", cfg.Payments},
		{"Email", cfg.Email},
		{"Package Manager", cfg.PackageManager},
		{"Deployment", cfg.Deployment},
	}

	// Filter out empty/"none" rows
	var filtered []row
	for _, r := range rows {
		if r.Value != "" && r.Value != "none" {
			filtered = append(filtered, r)
		}
	}

	if len(filtered) == 0 {
		return
	}

	b.WriteString("## Stack Summary\n\n")
	b.WriteString("| Layer | Choice |\n")
	b.WriteString("|-------|--------|\n")
	for _, r := range filtered {
		b.WriteString(fmt.Sprintf("| %s | %s |\n", r.Layer, r.Value))
	}
	b.WriteString("\n")
}

// writeEnvVars outputs a table of every environment variable with instructions
// on where to obtain the value.
func writeEnvVars(b *strings.Builder, cfg *config.ProjectConfig) {
	entries := collectEnvEntries(cfg)
	if len(entries) == 0 {
		return
	}

	b.WriteString("## Environment Variables\n\n")
	b.WriteString("| Variable | Where to Get It |\n")
	b.WriteString("|----------|----------------|\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("| `%s` | %s |\n", e.Variable, e.WhereToGet))
	}
	b.WriteString("\n")
}

// collectEnvEntries builds the environment variable reference list based on
// which services were selected in the project config.
func collectEnvEntries(cfg *config.ProjectConfig) []envEntry {
	var entries []envEntry

	// Database
	switch cfg.Database {
	case "prisma", "drizzle":
		entries = append(entries, envEntry{
			"DATABASE_URL",
			"Your database provider",
		})
	case "supabase":
		entries = append(entries,
			envEntry{"NEXT_PUBLIC_SUPABASE_URL", "[Supabase Dashboard](https://supabase.com/dashboard) > Settings > API"},
			envEntry{"NEXT_PUBLIC_SUPABASE_ANON_KEY", "[Supabase Dashboard](https://supabase.com/dashboard) > Settings > API"},
			envEntry{"SUPABASE_SERVICE_ROLE_KEY", "[Supabase Dashboard](https://supabase.com/dashboard) > Settings > API"},
		)
	case "mongodb-mongoose":
		entries = append(entries, envEntry{
			"MONGODB_URI",
			"[MongoDB Atlas](https://cloud.mongodb.com) > Database > Connect",
		})
	}

	// Auth
	switch cfg.Auth {
	case "clerk":
		entries = append(entries,
			envEntry{"NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY", "[Clerk Dashboard](https://dashboard.clerk.com) > API Keys"},
			envEntry{"CLERK_SECRET_KEY", "[Clerk Dashboard](https://dashboard.clerk.com) > API Keys"},
		)
	case "nextauth":
		entries = append(entries,
			envEntry{"NEXTAUTH_URL", "Set to `http://localhost:3000` for local dev"},
			envEntry{"NEXTAUTH_SECRET", "Run: `openssl rand -base64 32`"},
		)
	}

	// Payments
	if cfg.Payments == "stripe" {
		entries = append(entries,
			envEntry{"STRIPE_SECRET_KEY", "[Stripe Dashboard](https://dashboard.stripe.com) > Developers > API keys"},
			envEntry{"NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY", "[Stripe Dashboard](https://dashboard.stripe.com) > Developers > API keys"},
			envEntry{"STRIPE_WEBHOOK_SECRET", "[Stripe Dashboard](https://dashboard.stripe.com) > Developers > Webhooks"},
		)
	}

	// Email
	if cfg.Email == "resend" {
		entries = append(entries, envEntry{
			"RESEND_API_KEY",
			"[Resend Dashboard](https://resend.com/api-keys)",
		})
	}

	return entries
}

// writeManualSteps lists scaffold steps that still need manual action.
func writeManualSteps(b *strings.Builder, result *scaffold.Result) {
	var manual []scaffold.StepResult
	for _, s := range result.Steps {
		if s.Status == "manual" {
			manual = append(manual, s)
		}
	}

	if len(manual) == 0 {
		return
	}

	b.WriteString("## Manual Setup Steps\n\n")
	for i, s := range manual {
		b.WriteString(fmt.Sprintf("%d. **%s:** %s\n", i+1, s.Name, s.Message))
	}
	b.WriteString("\n")
}

// writeDevCommands outputs the relevant dev/build/lint/test commands for the
// selected framework and package manager.
func writeDevCommands(b *strings.Builder, cfg *config.ProjectConfig) {
	b.WriteString("## Development Commands\n\n")
	b.WriteString("```bash\n")

	pm := cfg.PackageManager
	if pm == "" {
		pm = "npm"
	}

	run := pm + " run "
	if pm == "bun" {
		run = "bun "
	}

	switch cfg.Framework {
	case "nextjs":
		b.WriteString(fmt.Sprintf("%sdev        # Start dev server\n", run))
		b.WriteString(fmt.Sprintf("%sbuild      # Production build\n", run))
		b.WriteString(fmt.Sprintf("%sstart      # Start production server\n", run))
		b.WriteString(fmt.Sprintf("%slint       # Run ESLint\n", run))
	case "react-vite", "sveltekit", "nuxt":
		b.WriteString(fmt.Sprintf("%sdev        # Start dev server\n", run))
		b.WriteString(fmt.Sprintf("%sbuild      # Production build\n", run))
		b.WriteString(fmt.Sprintf("%spreview    # Preview production build\n", run))
	case "django":
		b.WriteString("python manage.py runserver   # Start dev server\n")
		b.WriteString("python manage.py migrate     # Run migrations\n")
		b.WriteString("python manage.py test        # Run tests\n")
	case "fastapi":
		b.WriteString("uvicorn main:app --reload    # Start dev server\n")
		b.WriteString("pytest                       # Run tests\n")
	case "rails":
		b.WriteString("rails server       # Start dev server\n")
		b.WriteString("rails db:migrate   # Run migrations\n")
		b.WriteString("rails test         # Run tests\n")
	case "laravel":
		b.WriteString("php artisan serve      # Start dev server\n")
		b.WriteString("php artisan migrate    # Run migrations\n")
		b.WriteString("php artisan test       # Run tests\n")
	default:
		b.WriteString(fmt.Sprintf("%sdev        # Start dev server\n", run))
		b.WriteString(fmt.Sprintf("%sbuild      # Production build\n", run))
	}

	b.WriteString("```\n\n")
}

// writeDeployment outputs deployment instructions based on the configured target.
func writeDeployment(b *strings.Builder, cfg *config.ProjectConfig) {
	b.WriteString("## Deployment\n\n")

	switch cfg.Deployment {
	case "vercel":
		b.WriteString("Push to GitHub (auto-deploys if linked) or run:\n\n")
		b.WriteString("```bash\nvercel --prod\n```\n")
	case "railway":
		b.WriteString("1. Go to [railway.app](https://railway.app) and create a new project\n")
		b.WriteString("2. Deploy from your GitHub repository\n")
		b.WriteString("3. Add environment variables in the Railway dashboard\n")
	case "cloudflare":
		b.WriteString("1. Go to the [Cloudflare Pages dashboard](https://dash.cloudflare.com/?to=/:account/pages)\n")
		b.WriteString("2. Create a new project and connect your GitHub repository\n")
		b.WriteString("3. Set the build command and output directory for your framework\n")
	case "docker":
		b.WriteString("Build and run with Docker:\n\n")
		b.WriteString("```bash\n")
		b.WriteString(fmt.Sprintf("docker build -t %s .\n", cfg.Name))
		b.WriteString(fmt.Sprintf("docker run -p 3000:3000 %s\n", cfg.Name))
		b.WriteString("```\n")
	default:
		b.WriteString("No specific deployment target configured.\n")
	}

	b.WriteString("\n")
}

// writeArchNotes outputs a brief description of how the selected pieces connect.
func writeArchNotes(b *strings.Builder, cfg *config.ProjectConfig) {
	b.WriteString("## Architecture Notes\n\n")

	// Framework + language
	if cfg.Framework != "" && cfg.Framework != "none" {
		b.WriteString(fmt.Sprintf("This is a **%s** project", cfg.Framework))
		if cfg.Language != "" && cfg.Language != "none" {
			b.WriteString(fmt.Sprintf(" written in **%s**", cfg.Language))
		}
		b.WriteString(".\n\n")
	} else if cfg.Language != "" && cfg.Language != "none" {
		b.WriteString(fmt.Sprintf("This is a **%s** project.\n\n", cfg.Language))
	}

	// Database
	switch cfg.Database {
	case "prisma":
		b.WriteString("**Database:** Uses Prisma ORM for type-safe database access. Schema is defined in `prisma/schema.prisma`. Run `npx prisma migrate dev` to apply changes.\n\n")
	case "drizzle":
		b.WriteString("**Database:** Uses Drizzle ORM for lightweight, type-safe SQL. Define your schema in TypeScript and push with `drizzle-kit push`.\n\n")
	case "supabase":
		b.WriteString("**Database:** Uses Supabase for managed Postgres with built-in auth and real-time subscriptions. Access via the `@supabase/supabase-js` client.\n\n")
	case "mongodb-mongoose":
		b.WriteString("**Database:** Uses MongoDB with Mongoose ODM for schema validation and data modeling.\n\n")
	}

	// Auth
	switch cfg.Auth {
	case "clerk":
		b.WriteString("**Auth:** Clerk handles authentication and user management. Middleware protects routes via `@clerk/nextjs`.\n\n")
	case "nextauth":
		b.WriteString("**Auth:** NextAuth.js provides flexible authentication with support for multiple providers. Configure providers in your auth config file.\n\n")
	case "lucia":
		b.WriteString("**Auth:** Lucia provides a lightweight, session-based authentication library.\n\n")
	}

	// Payments
	if cfg.Payments == "stripe" {
		b.WriteString("**Payments:** Stripe handles payment processing. Use `stripe` on the server and `@stripe/stripe-js` on the client. Set up webhook endpoints to handle async events.\n\n")
	}

	// Email
	if cfg.Email == "resend" {
		b.WriteString("**Email:** Resend provides transactional email delivery. Use the `resend` package to send emails from your API routes or server actions.\n\n")
	}

	// Styling
	switch cfg.Styling {
	case "tailwind":
		b.WriteString("**Styling:** Tailwind CSS for utility-first styling.\n\n")
	case "tailwind-shadcn":
		b.WriteString("**Styling:** Tailwind CSS with shadcn/ui for pre-built, customizable components.\n\n")
	}
}
